name: TENT
favicon: null
layout_spectrum: 0.71035
typography_spectrum: 0.35862
title: 'TENT:  A Creative Outpost'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75c3d7'
    - '#ee545d'
    - '#f1767d'
    - '#f6afb2'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
