name: TENT
favicon: null
layout_spectrum: 0.84138
typography_spectrum: 0.5931
title: TENT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75bdc9'
    - '#dc4f58'
    - '#f2c8c2'
    - '#e7878b'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.44628734258003533
purpose: []
