name: TENT
favicon: null
layout_spectrum: 0.7194919919129461
typography_spectrum: 0.10110722784884274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75c3d7'
    - '#ee545d'
    - '#f1767d'
    - '#f6afb2'
  brandStrength: 1
  lightness: 0.1450688410550356
  saturation: 0.039810029324144125
  rhythmicContrast: 0.44628734258003533
purpose: []
